language: objective-c
os: osx
osx_image: xcode7.3

env:
    global:
        - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=1
    matrix:
        - MATRIX_TARGET="-scheme Beeradex -sdk iphonesimulator"

script:
    - set -o pipefail
    - xcodebuild clean test Beeradex.xcworkspace $MATRIX_TARGET GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty

after_success:
    - bash <(curl -s https://codecov.io/bash)